### ISSUE TITLE
The adapter should support SampledFunctionParameterType to arrays mapping/transfer

### ISSUE THREAD

**Issue by nathanatrhea** [RHEAGROUP/DEH-ECOSIMPRO#62]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the DEHP-EcosimPro
- [x] I have searched [open](https://github.com/RHEAGROUP/DEHP-ECOSIMPRO/issues) and [closed](https://github.com/RHEAGROUP/DEHP-ECOSIMPRO/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

The  adapter currently doesn't let the user select the whole valueset set or multiple values from a SampledFunctionParameterType. In fact only one to one mapping is doable from Hub to Dst.

To overcome this, the adapter should let the user select a source the whole valueset from a SFPT or a part of it to map to a opc array variable type.

The way arrays are handled in a opc server is that for each array index one variable is there. 
Example: arrayvar[0,0],  arrayvar[0,1],  arrayvar[1,0],  arrayvar[1,1] ...

So by selecting any one of one opc array variable, the adapter should then automatically determine:

- Which variables are concerned (belongs to the same array)
- The dimension of the array
- Is the valueset or the selection fits

### Tasks
- [ ] Create a VariableRowVariable that represents a collection of variable. 
- [ ] Update the MappedElementDefinitionRowViewModel so it can store mapping of arrays ?
- [ ] Updates the Mapping configuration dialog
   - [ ] Allow mapping only dimensional compatible parameter
- [ ] Saving the mapping
- [ ] Ensuring that the loading of saved mapping works with mapping that maps SFPT to OPC Arrays 
- [ ] Tests

### System Configuration

- DEHPCommon version:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by nathanatrhea** [comment]
![image](https://user-images.githubusercontent.com/61700723/132325125-9bd3ec22-3fad-44a0-aa35-40603f831cd6.png)
Proposed solution
